apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restored-pvc-fail
  namespace: namespace2
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: snapshot.storage.k8s.io
    kind: VolumeSnapshot
    name: secret-snapshot # Name not in the allowlist
    namespace: namespace1
